replicaCount: 1

image:
  repository: vbabichev/slo-app
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: slo-app.local
      paths: []

resources: {}
tolerations: []
affinity: {}

metrics:
  scanInterval: 10s
  port: web

alertRules: {}
recordRules: {}
