ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: slo-app.host
      paths: ["/"]

alertRules:
  - alert: VersionAlert
    expr: version{job="metrics-app"} != 1

  - alert: NoTrafficFlowing
    expr: rate(opencensus_io_http_server_request_count{job="slo-app"}[5m]) < 100

  - alert: 90%ile of requests processed in less then 0.001 sec
    expr: histogram_quantile(0.9, rate(opencensus_io_http_server_latency_bucket{job="slo-app"}[5m])) > 1

  - alert: 99.9%ile of requests processed in less then 0.05 sec
    expr: histogram_quantile(0.999, rate(opencensus_io_http_server_latency_bucket{job="slo-app"}[5m])) > 2

  - alert: SLO - Error requests to overall request ratio shouldn't exceed 5%
    expr: sli:errors_per_request:ratio_rate5m{job="slo-app"} * 100 > 5

recordRules:
  - record: sli:errors_per_request:ratio_rate5m
    expr: sum without(http_status) (rate(opencensus_io_http_server_response_count_by_status_code{job="slo-app", http_status !~ "2[0-9]{2}"}[5m])) / ignoring(pod) rate(opencensus_io_http_server_request_count{job="slo-app"}[5m])
