{{- if .Values.alertRules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "slo-app.fullname" . }}
  labels:
    release: prometheus-operator # Hack
    {{- include "slo-app.labels" . | nindent 4 }}
spec:
  groups:
  - name: {{ include "slo-app.fullname" . }}-alertRules
    rules:
    {{- toYaml .Values.alertRules | nindent 4 }}
  - name: {{ include "slo-app.fullname" . }}-recordRules
    rules:
    {{- toYaml .Values.recordRules | nindent 4 }}
{{- end }}
